### ISSUE TITLE
DISABLE_MISS_PENALTY no longer works on 1.0.7

### ISSUE THREAD

**Issue by theFoxley** [LunarClient/Apollo#105]
On the spigot config, even if i update the config file combat setting from "competitive-game" to "disable-miss-penalty" the setting is not working.

I can't exceed the 20 cps limit while hitting air (1.8 behavior) even with a 40 cps autoclicker: 
![image](https://github.com/LunarClient/Apollo/assets/7950977/1129cdbb-3126-4c1e-9a11-c849d941c366)

**Comment by TrentinTheKid** [comment]
I believe this issue has been resolved. Do you mind testing it again?

There was a slight desync between our client deploy and the updated config key. Since Lunar Client is deployed using a canary, it takes some time to be fully rolled out to all users. Usually, this isn't an issue, but in this case, we had to update an existing key.
